# Generated by Django 5.2.11 on 2026-02-22 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_reply_search_receipts_theme'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_room_id_645da7_idx',
            old_name='msg_room_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_room_id_481454_idx',
            old_name='msg_room_type_idx',
        ),
        migrations.RenameIndex(
            model_name='messagereceipt',
            new_name='chat_messag_message_f96e0d_idx',
            old_name='rcpt_msg_sess_idx',
        ),
        migrations.RenameIndex(
            model_name='messagereceipt',
            new_name='chat_messag_message_00343d_idx',
            old_name='rcpt_msg_del_idx',
        ),
        migrations.RenameIndex(
            model_name='messagereceipt',
            new_name='chat_messag_message_26bab1_idx',
            old_name='rcpt_msg_seen_idx',
        ),
        migrations.RenameIndex(
            model_name='roompresence',
            new_name='chat_roompr_room_id_018f7e_idx',
            old_name='chat_roompr_room_id_1e6107_idx',
        ),
        migrations.RenameIndex(
            model_name='roompresence',
            new_name='chat_roompr_room_id_9b8a15_idx',
            old_name='chat_roompr_room_id_3b02fa_idx',
        ),
        migrations.RenameIndex(
            model_name='roomverifiedbadge',
            new_name='chat_roomve_room_id_7a2f21_idx',
            old_name='badge_room_sess_idx',
        ),
    ]
