# Generated by Django 5.2.11 on 2026-02-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_msg_room_ts_idx_chat_messag_room_id_645da7_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereceipt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='messagereceipt',
            name='message',
        ),
        migrations.AlterUniqueTogether(
            name='roomverifiedbadge',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='roomverifiedbadge',
            name='room',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_room_id_645da7_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_room_id_481454_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_is_admin',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_is_verified',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_session_key',
        ),
        migrations.DeleteModel(
            name='MessageReceipt',
        ),
        migrations.DeleteModel(
            name='RoomVerifiedBadge',
        ),
    ]
